apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-tekton-annotation-pipelinerun
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: check-pipelinerun-annotation
    match:
      any:
      - resources:
          kinds:
          - PipelineRun
    preconditions:
      all:
      - key: "{{ request.operation || 'BACKGROUND' }}"
        operator: Equals
        value: CREATE
    validate:
      message: "PipelineRun annotation should not have max-keep-runs value more than 3."
      pattern:
        metadata:
          annotations:
            pipelinesascode.tekton.dev/max-keep-runs: "<3"