apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-tekton-name-pipelinerun
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: check-pipelinerun-name
    match:
      any:
      - resources:
          kinds:
          - PipelineRun
    preconditions:
      all:
      - key: "{{ request.operation || 'BACKGROUND' }}"
        operator: Equals
        value: CREATE
    validate:
      message: "A generateName is required."
      pattern:
        metadata:
          generateName: "?*"