# apiVersion: kyverno.io/v1
# kind: ClusterPolicy
# metadata:
#   name: require-vuln-scan
#   annotations:
#     policies.kyverno.io/title: Check Deployment Vulnerability Scan
#     policies.kyverno.io/category: Kubernetes
#     policies.kyverno.io/severity: medium
#     policies.kyverno.io/subject: Deployment
#     kyverno.io/kyverno-version: 1.10.0
#     policies.kyverno.io/minversion: 1.10.0
#     kyverno.io/kubernetes-version: "1.23"
#     policies.kyverno.io/description: >-
#       A signed bundle is required
# spec:
#   validationFailureAction: enforce
#   webhookTimeoutSeconds: 30
#   rules:
#   - name: check-signature
#     match:
#       resources:
#         kinds:
#         - Deployment 
#     imageExtractors:
#       Deployment:
#         - name: "deploymentspec"
#           path: "/spec/template/spec/containers/*"
#           value: "image"
#     verifyImages:
#     - imageReferences:
#       - "*"
#       attestors:
#       - entries:
#         - keys:
#             publicKeys: |-
#               -----BEGIN PUBLIC KEY-----
#               MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAENjFBjJyaqWwpvMb+oYys5CL12EL7
#               mFGqoLDBMfWDwXRFuIiNtJTNHRQdlRPk3P7bKKYFFR2KeVs6fn0Bh0Fo6g==
#               -----END PUBLIC KEY-----

---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: check-image
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "*"
        attestors:
        - count: 1
          entries:
          - keys:
              publicKeys: |-
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEZax6i/VHfeGjy41uvztHhGp4sm7g
                k6vFvHLIyJuJY16wNwvlJCwbkHQdF7sHHQgratw2MmAntQ9tox63EEvxLw==
                -----END PUBLIC KEY-----